### ISSUE TITLE
Stats are misleading

### ISSUE THREAD

**Issue by calebdw** [HwangTaehyun/github-repository-contribution-stats#16]
First off, thanks for sharing this---I love it!

For reference, here are my stats:

![image](https://github.com/HwangTaehyun/github-repository-contribution-stats/assets/4176520/ec2a525e-a35b-4d65-ab5a-f74c22785dde)

These are supposed to be my "Contributor Stats", so I would expect these to be *the stats of my personal contributions to the repos* (i.e., if you've contributed more than 95% of anyone else to a particular repo, then you would have an `S+` rank for that repo).

Instead, this is simply just a star count of the repos I've contributed to, which doesn't really tell me much in terms of my personal stats. For instance, I've only made one PR to `tree-sitter` (and a small one at that), and yet it shows up second on the list like I've contributed a bunch to it.

A stat that would be useful would be to take the percentage of my commits against the total number of commits to a repo for that year (or total if that's the config option) and rank that.

Thanks!

**Comment by calebdw** [comment]
@HwangTaehyun, it seems to me that the entire point of this banner is to show the *contributor's* stats. If a user merely contributes a typo fix to the Laravel Framework, that's likely to cause it to shoot to the top of their list with an S+ rating because it's a popular framework---despite not having any meaningful contributions.

It's not as simple as adding a second column because the entire ordering of the list would have to change.

*On the other hand*, you could show the user's contribution score in the first column,  and the repo score in the second column:

| Repo | Contributor Score | Repo Score |
| ---------| -------------------------- | -------------------  |
| Laravel/Framework | B | S+ |

This now paints the full picture, how much a user contributes to a certain project and the popularity of that project. The ordering should also take into account both scores---for example a B contributor score in a S+ project would hold much more weight than an S+ contributor score in a C project

**Comment by HwangTaehyun** [comment]
@calebdw Nice Idea!
I implemented the code querying the user's contribution commits to the repo and the total commits of the repo.

There is one thing to worry about. If you have any ideas for the contribution rank system, can you share them?

If the total commit of the repo is 10000 and the personal contribution commit is 1000, then the contribution portion is 1000/10000. It's 10% and some think it is low but if this repo is very popular and many people contribute this repo, this portion is relatively high.

However, it's too complicated to consider this.

Should we just simply do this?: S if it is more than 30%, A if it is more than 20%, B if it is more than 10%?

**Comment by calebdw** [comment]
@HwangTaehyun,

Awesome! I didn't think about the complications of calculating everyone's score with respect to all the others. But after thinking about this some more,  I realized that Github already ranks user's contributions to a repo:

![Screenshot_20240505_150646_Brave](https://github.com/HwangTaehyun/github-repository-contribution-stats/assets/4176520/a9583eef-d3cf-41fc-afb4-8baa329f5f2b)

All you would have to do is grab the list of contributors to a repo and see where they're ranked in the list---your normal scores could then apply (e.g., top 1% for S+, 90% for A, etc or whatever they actually are).

**Comment by HwangTaehyun** [comment]
@calebdw I added this feature. Check it out!
However, this feature requires this github API (https://api.github.com/repos/${nameWithOwner}/contributors?page=${page}&per_page=100) and this has API query limit of 5000 for free accounts per hour.
So, if this has reached to limit then it shows contributor rank to B.
You should apply your vercel server for better working!

**Comment by calebdw** [comment]
@HwangTaehyun, this looks awesome! Thanks!

![image](https://github.com/HwangTaehyun/github-repository-contribution-stats/assets/4176520/a78437d5-310b-4c84-bde5-936ebf87987d)


A couple of suggestions for improvement:
- swap the columns since the most important info here is the user's contributions to the project
  - the repos still seem to be sorted by the stars instead of the user's contributions (although all of my repos are showing up as B so it's possible that this has bee corrected), but really they should be weighted based on the user's contributions and the repo stars---for example, a B+ contribution score on a 10000+ project holds a lot more street cred than a S+ contribution score on a 1 star project
- if a user doesn't show up on the top 100 contributors to a project then that project shouldn't show up on the rankings because they haven't made enough meaningful contributions to that repo
- there's no need to filter over the list of users to find everyone that has more contributions **because they're already ordered from greatest to least**---all you have to do is find the user's index in the array:
  ![image](https://github.com/HwangTaehyun/github-repository-contribution-stats/assets/4176520/3ed2f5f2-39ca-40bd-9f70-cca440ae1cca)

**Comment by HwangTaehyun** [comment]
@calebdw Your correct rank is the following stats.
<img width="456" alt="image" src="https://github.com/HwangTaehyun/github-repository-contribution-stats/assets/42465090/357e3eaa-5332-4819-b70d-8e8ebbc42feb">
However, sometimes the API limit is reached then all ranks seem to show B. 
I changed hide_contributor_rank's default value to true to prevent API limit.

**Comment by HwangTaehyun** [comment]
@calebdw Yeah, you are right.
It's enough to get only 100 contributors and we can calculate the rank by only counting users who have more commit contributions than you contributed.

**Comment by calebdw** [comment]
@HwangTaehyun, I just updated to show the contributions and switch the column order, but they all show S+ contributions lol:

![image](https://github.com/HwangTaehyun/github-repository-contribution-stats/assets/4176520/873da0a9-9e0b-4074-b3e7-cbe07174960d)

**Comment by HwangTaehyun** [comment]
<a href="https://github.com/HwangTaehyun/github-contributor-stats">![Taehyun's GitHub Contributor stats](https://github-contributor-stats.vercel.app/api?username=calebdw&combine_all_yearly_contributions=true&hide=B,B+&theme=swift&hide_contributor_rank=false)</a>

<img width="609" alt="image" src="https://github.com/HwangTaehyun/github-repository-contribution-stats/assets/42465090/9504636b-558e-4fef-bf70-12844a4234a0">
