### ISSUE TITLE
vercel issues

### ISSUE THREAD

**Issue by orcutt989** [HwangTaehyun/github-repository-contribution-stats#18]
When I try my own username on your Vercel I get...
```md
![](https://github-contributor-stats.vercel.app/api?username=orcutt989)
```
![](https://github-contributor-stats.vercel.app/api?username=orcutt989)

I tried hosting it on Vercel myself in case it was a rate limit problem and get this error.
```md
![](https://github-repository-contribution-stats-mu.vercel.app/api?username=orcutt989)
```
![](https://github-repository-contribution-stats-mu.vercel.app/api?username=orcutt989)

**Comment by HwangTaehyun** [comment]
@orcutt989 I will check it and get back to you!

**Comment by orcutt989** [comment]
What about with your hosted version? Shouldnt it work with https://github-contributor-stats.vercel.app/api?username= ?
